### PR TITLE
N°5796 - Fix typo in ActionWebhook::GetRemoteApplicationConnectionFromActionWebhok()

### PR DESCRIPTION
**Pull request by Hipska**
No impact in current module as the method is not used.

### CODE REVIEW

**Review by Molkobain — APPROVED** [review]

**Comment by Hipska** [comment]
I don't see why anyone would use this method, as they can as wel just call the used method on `$oAction` directly..

**Comment by Molkobain** [comment]
Actually I think this method doesn't make any sense and was added during the early stages of the module development. We could completely remove it.

> I don't see why anyone would use this method, as they can as wel just call the used method on `$oAction` directly..

Yes, but we have a deprecation/remove policy for any public "API" to avoid BC breaks as much as possible. So we tend to apply it to everything. But in this case I feel like it could be overlooked.

**Comment by Molkobain** [comment]
Accepted during technical review.

**Comment by Molkobain** [comment]
Accepted during functional review.

**Pull request merged**
